language: java

before_install:
  - cd backend
  
jdk:
  - oraclejdk8

branches:
  only:
     - master
     - desenvolvimento

addons:
  sonarqube:
    token: 1abeb36b5e88237bb32d141cfb832530df398359
    
script:
  - mvn test -B
  - sonar-scanner

notifications:
  slack: trabalho-de-les-20171:VPGJMy9q3QpahFd5WXIQ6xTG
