language: python

matrix:
  include:
  - python: 3.6
  - language: java
    jdk: oraclejdk8

branches:
  only:
     - master
     - desenvolvimento
     
install:
    - sudo pip install -r requirements.txt
    - sudo python setup.py sdist

addons:
  sonarqube:
    organization: amandapersampa-github
    token: 1abeb36b5e88237bb32d141cfb832530df398359
    
script:
    - pytest
    - sonar-scanner

notifications:
  slack: trabalho-de-les-20171:VPGJMy9q3QpahFd5WXIQ6xTG
