CREATE TABLE CARDAPIO
(
  ID_CARDAPIO SERIAL PRIMARY KEY,
  ITEM_COD INTEGER
);

CREATE TABLE PRODUTO(
  ID_PRODUTO SERIAL PRIMARY KEY,
  NOME VARCHAR(30),
  QUANTIDADE INTEGER,
  UNIDADE VARCHAR(10)
);

CREATE TABLE COMPRA(
  ID_COMPRA SERIAL PRIMARY KEY,
  QUANTIDADE INTEGER,
  DIA DATE,
  ID_PRODUTO INTEGER
);

CREATE TABLE ITEM_CARDAPIO(
  ID_ITEM_CARDAPIO SERIAL PRIMARY KEY,
  NOME INTEGER,
  PRECO  DECIMAL,
  ID_PRODUTO INTEGER
);

CREATE TABLE PEDIDO(
  ID_PEDIDO SERIAL PRIMARY KEY,
  ID_ITEM_CARDAPIO INTEGER
);

CREATE TABLE RESTAURANTE(
  ID_RESTAURANTE SERIAL PRIMARY KEY,
  ID_CARDAPIO INTEGER,
  ID_PESSOA INTEGER,
  ID_DESPESA INTEGER
);

CREATE TABLE DESPESA(
  ID_DESPESA SERIAL PRIMARY KEY,
  DATA_PAGAMENTO DATE,
  DATA_VENCIMENTO DATE,
  VLD_TIPO_DESPESA INTEGER
);

CREATE TABLE FUNCIONARIO(
  ID_FUNCIONARIO SERIAL PRIMARY KEY,
  NOME VARCHAR(50),
  TELEFONE DECIMAL,
  CPF DECIMAL
);