"""empty message

Revision ID: 05e53de75966
Revises: 
Create Date: 2017-07-02 21:21:47.048000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e53de75966'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidademedida',
    sa.Column('id_unidade_medida', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_unidade_medida'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('produto',
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('qtd_minima', sa.Integer(), nullable=True),
    sa.Column('item_estoque_vld', sa.String(), nullable=True),
    sa.Column('id_unidade_medida', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_unidade_medida'], ['unidademedida.id_unidade_medida'], ),
    sa.PrimaryKeyConstraint('id_produto'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('compra',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('itemcardapio',
    sa.Column('id_item_cardapio', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('qtd_ingrediente', sa.Integer(), nullable=True),
    sa.Column('qtd_item_extra', sa.Integer(), nullable=True),
    sa.Column('tipo_item', sa.String(), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_item_cardapio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemcardapio')
    op.drop_table('compra')
    op.drop_table('produto')
    op.drop_table('unidademedida')
    # ### end Alembic commands ###
