"""empty message

Revision ID: 658a772291ef
Revises: 
Create Date: 2017-07-02 18:42:35.223381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658a772291ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemcardapio',
    sa.Column('id_item_cardapio', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('qtd_ingrediente', sa.Integer(), nullable=True),
    sa.Column('qtd_item_extra', sa.Integer(), nullable=True),
    sa.Column('tipo_item', sa.String(), nullable=True),
    sa.Column('item_extra', sa.String(), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_item_cardapio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemcardapio')
    # ### end Alembic commands ###
