"""empty message

Revision ID: b7821433e623
Revises: 
Create Date: 2017-07-04 20:53:26.079416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7821433e623'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesa',
    sa.Column('id_despesa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_despesa')
    )
    op.add_column('itemcardapio', sa.Column('item_extra', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemcardapio', 'item_extra')
    op.drop_table('despesa')
    # ### end Alembic commands ###
